name = "cloud-resume-worker"
main = "src/index.js"
compatibility_date = "2023-10-25"

[vars]
# Replace this with your actual Azure Static Website Endpoint
# https://storagesamueladebodun.z13.web.core.windows.net/
AZURE_STORAGE_URL = "https://storagesamueladebodunv2.web.core.windows.net/"
# Replace with actual Function URL after deployment
AZURE_FUNCTION_URL = ""
